#!/usr/bin/env python3
"""FoneClaw v2 Multi-page build - SEO-optimized separate URLs"""
import pickle, os, json

base = '/home/administrator/clawfone-v2'
cache = pickle.load(open(os.path.join(base, '_build_cache.pkl'), 'rb'))
imgs = cache['imgs']
icon_b64 = cache['icon_b64']

# Auto-compress images before building
import sys
import os as _sys
import article_publish_dates
from article_publish_dates import ARTICLE_PUBLISH_DATES
from article_publish_dates import ARTICLE_PUBLISH_DATES
sys.path.insert(0, base)
from compress_images import compress_cache_images
_before, _after, _count = compress_cache_images(os.path.join(base, '_build_cache.pkl'))
if _count > 0:
    print(f"  Images compressed: {_before//1024}KB -> {_after//1024}KB ({_count} images)")
    cache = pickle.load(open(os.path.join(base, '_build_cache.pkl'), 'rb'))
    imgs = cache['imgs']
translations = json.load(open(os.path.join(base, 'translations.json')))

# Import SEO-optimized articles (generated by Gemini 3.1 Pro Preview)
import importlib.util
def load_batch(fname):
    spec = importlib.util.spec_from_file_location("batch", os.path.join(base, fname))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.BATCH

articles_data = []
for i in range(1, 11):
    articles_data.extend(load_batch(f'articles_batch{i}.py'))
# Load batch10b and 10c (separate files)
try:
    articles_data.extend(load_batch('articles_batch10b.py'))
except: pass
try:
    articles_data.extend(load_batch('articles_batch10c.py'))
except: pass
try:
    articles_data.extend(load_batch('articles_batch10d.py'))
except: pass
try:
    articles_data.extend(load_batch('articles_batch11.py'))
except: pass
try:
    articles_data.extend(load_batch('articles_batch12.py'))
except: pass
try:
    articles_data.extend(load_batch('articles_batch131.py'))
except Exception as e:
    print(f"Warning: Could not load batch131: {e}")
try:
    articles_data.extend(load_batch('articles_batch132.py'))
except Exception as e:
    print(f"Warning: Could not load batch132: {e}")
try:
    articles_data.extend(load_batch('articles_batch133.py'))
except Exception as e:
    print(f"Warning: Could not load batch133: {e}")

# Load batch14
for i in range(1, 6):
    try:
        articles_data.extend(load_batch(f'articles_batch14{i}.py'))
    except Exception as e:
        print(f"Warning: Could not load batch14{i}: {e}")

# Load batch15
for i in range(1, 6):
    try:
        articles_data.extend(load_batch(f'articles_batch15{i}.py'))
    except Exception as e:
        print(f"Warning: Could not load batch15{i}: {e}")

# Load batch156 (AI Notification Management)
try:
    articles_data.extend(load_batch('articles_batch156.py'))
except Exception as e:
    print(f"Warning: Could not load batch156: {e}")

# Load batch16 (Xiaomi Lobster Phone)
try:
    articles_data.extend(load_batch('articles_batch_xiaomi_lobster.py'))
except Exception as e:
    print(f"Warning: Could not load xiaomi_lobster: {e}")

# Load new articles (Gemini Intelligence, Tencent, Xiaomi)
try:
    articles_data.extend(load_batch("articles_batch_tencent_cost.py"))
    articles_data.extend(load_batch("articles_batch_xiaomi_summit.py"))
    articles_data.extend(load_batch("articles_batch_foneclaw_vs_likeclaw.py"))
    articles_data.extend(load_batch("articles_batch_foneclaw_vs_apple_intelligence.py"))
    articles_data.extend(load_batch("articles_batch_apple_intelligence_accessibility_foneclaw.py"))
    articles_data.extend(load_batch("articles_batch_foneclaw_vs_samsung_galaxy_ai.py"))
    articles_data.extend(load_batch("articles_batch_ai_phone_agent_harness.py"))
    articles_data.extend(load_batch("articles_batch_mediatek_dimensity_phone_agent.py"))
    
    articles_data.extend(load_batch("articles_batch_ios_27_siri_ai_agent.py"))
    articles_data.extend(load_batch("articles_batch_ios27_gemini.py"))
    articles_data.extend(load_batch("articles_batch_copilot_trends.py"))
    articles_data.extend(load_batch("articles_batch_agent_spending.py"))
    articles_data.extend(load_batch("articles_batch_gemini_intelligence_pixel_9_excluded.py"))
    articles_data.extend(load_batch("articles_batch_gemini_intelligence_supported_devices.py"))
    articles_data.extend(load_batch("articles_batch_samsung_galaxy_s26_ai_features_s25.py"))
    articles_data.extend(load_batch("articles_batch_foneclaw_vs_openally.py"))
    articles_data.extend(load_batch("articles_batch_foneclaw_vs_minimax.py"))
    articles_data.extend(load_batch("articles_batch_foneclaw_vs_all_in_one_ai_agent.py"))
    articles_data.extend(load_batch("articles_batch_foneclaw_vs_nebula_ai.py"))
    articles_data.extend(load_batch("articles_batch_skyclaw_vs_foneclaw.py"))
    articles_data.extend(load_batch("articles_batch_foneclaw_vs_adobe_firefly.py"))
    articles_data.extend(load_batch("articles_batch_cloud_local.py"))
    articles_data.extend(load_batch("articles_batch_superapp.py"))
    articles_data.extend(load_batch("articles_batch_hymem.py"))
    articles_data.extend(load_batch("articles_batch_workbuddy.py"))
    articles_data.extend(load_batch("articles_batch_build.py"))
    articles_data.extend(load_batch("articles_batch_nvidia.py"))
    articles_data.extend(load_batch("articles_batch_glasses.py"))
    articles_data.extend(load_batch("articles_batch_raybans.py"))
    articles_data.extend(load_batch("articles_batch_discover.py"))
    articles_data.extend(load_batch("articles_batch_trust.py"))
    articles_data.extend(load_batch("articles_batch_enterprise.py"))
    articles_data.extend(load_batch("articles_batch_token.py"))
    articles_data.extend(load_batch("articles_batch_lab_to_pocket.py"))
    articles_data.extend(load_batch("articles_batch_security.py"))
    articles_data.extend(load_batch("articles_batch_spark.py"))
    articles_data.extend(load_batch("articles_batch_wwdc.py"))
    articles_data.extend(load_batch("articles_batch_context.py"))
    articles_data.extend(load_batch("articles_batch_mcp.py"))
    articles_data.extend(load_batch("articles_batch_apple_local.py"))
    articles_data.extend(load_batch("articles_batch_app_intents.py"))
    articles_data.extend(load_batch("articles_batch_ai_pro.py"))
    articles_data.extend(load_batch("articles_batch_scout.py"))
    articles_data.extend(load_batch("articles_batch_os_agent_foundation.py"))
    articles_data.extend(load_batch("articles_batch_ai_chip_race.py"))
    articles_data.extend(load_batch("articles_batch_self_improving.py"))
    articles_data.extend(load_batch("articles_batch_eval_driven.py"))
    articles_data.extend(load_batch("articles_batch_closed_loop.py"))
    articles_data.extend(load_batch("articles_batch_llm_optimization.py"))
    articles_data.extend(load_batch("articles_batch_os_agent_traffic.py"))
    articles_data.extend(load_batch("articles_batch_openai_no_app.py"))
    articles_data.extend(load_batch("articles_batch_dev_guide.py"))
    articles_data.extend(load_batch("articles_batch_voice_first.py"))
    articles_data.extend(load_batch("articles_batch_voice_control_hub.py"))
except Exception as e:
    print(f"Warning: Could not load new_articles: {e}")

# Load MiClaw review batch
try:
    articles_data.extend(load_batch("articles_batch_miclaw_review.py"))
except Exception as e:
    print(f"Warning: Could not load miclaw_review: {e}")

# Load Gemini Intelligence & Notification batches
try:
    articles_data.extend(load_batch("batch_gemini-intelligence-form-filling.py"))
except Exception as e:
    print(f"Warning: Could not load gemini-intelligence-form-filling: {e}")

try:
    articles_data.extend(load_batch("batch_gemini-intelligence-widgets.py"))
except Exception as e:
    print(f"Warning: Could not load gemini-intelligence-widgets: {e}")

try:
    articles_data.extend(load_batch("batch_ai_notification.py"))
except Exception as e:
    print(f"Warning: Could not load ai_notification: {e}")

try:
    articles_data.extend(load_batch("articles_batch_1000_tps_phone_agent.py"))
except Exception as e:
    print(f"Warning: Could not load 1000_tps_phone_agent: {e}")

try:
    articles_data.extend(load_batch("articles_batch_jd_tencent_ai_agent.py"))
except Exception as e:
    print(f"Warning: Could not load jd_tencent_ai_agent: {e}")

try:
    articles_data.extend(load_batch("articles_batch_wechat_ai_agent.py"))
except Exception as e:
    print(f"Warning: Could not load wechat_ai_agent: {e}")

try:
    articles_data.extend(load_batch("articles_batch_claude_code_multi_agent.py"))
except Exception as e:
    print(f"Warning: Could not load claude_code_multi_agent: {e}")

print(f"Loaded {len(articles_data)} SEO-optimized articles")

# Load share text mapping
try:
    from share_text_data import SHARE_TEXT
    # Normalize all articles to 6 elements, then add share_text
    normalized = []
    for item in articles_data:
        if len(item) >= 7:
            base_item = item[:6]  # batch7 has 7 elements, normalize to 6
        else:
            base_item = item
        normalized.append(base_item)
    articles_data = normalized
    
    # Add share_text to each article
    enriched_data = []
    for item in articles_data:
        slug = item[0]
        share_text = SHARE_TEXT.get(slug, '')
        enriched_data.append(item + (share_text,))
    articles_data = enriched_data
    print(f"Loaded {len(articles_data)} SEO-optimized articles with share_text")
except Exception as e:
    print(f"Error loading share_text: {e}")


# === 验证并修复article_keywords_data格式 ===
_kw_file = os.path.join(base, "article_keywords_data.py")
with open(_kw_file, "r") as _f:
    _kw_content = _f.read()
    _kw_lines = _kw_content.splitlines(True)

# 找到字典结束位置（最后一个}）
_dict_end = None
for i, line in enumerate(_kw_lines):
    if line.strip() == "}":
        _dict_end = i

if _dict_end is not None:
    # 检查字典外面是否有关键词
    _outside_count = 0
    for i, line in enumerate(_kw_lines[_dict_end + 1:], start=_dict_end + 1):
        stripped = line.strip()
        if stripped and stripped.startswith("'") and ":" in stripped and "[" in stripped:
            _outside_count += 1
    
    if _outside_count > 0:
        print(f"\u26a0\ufe0f article_keywords_data.py\u683c\u5f0f\u9519\u8bef\uff1a{_outside_count}\u4e2a\u5173\u952e\u8bcd\u5728\u5b57\u5178\u5916\u9762\uff0c\u6b63\u5728\u81ea\u52a8\u4fee\u590d...")
        # 直接删除字典外面的内容（保留到最后一个}）
        _new_content = "\n".join(_kw_lines[:_dict_end + 1]) + "\n"
        with open(_kw_file, "w") as _f:
            _f.write(_new_content)
        print("\u2705 \u5df2\u81ea\u52a8\u4fee\u590d")

# === 检测slug重复 ===
_slug_set = set()
_slug_dupes = []
for _item in articles_data:
    _slug = _item[0]
    if _slug in _slug_set:
        _slug_dupes.append(_slug)
    _slug_set.add(_slug)
if _slug_dupes:
    print(f"⚠️ 警告：发现重复的slug: {', '.join(_slug_dupes)}")
    print(f"   重复的slug会导致文章被覆盖！")
    print(f"   请检查batch文件，确保每个slug唯一。")

# === 自动修复article_publish_dates格式 ===
_pd_file = os.path.join(base, "article_publish_dates.py")
try:
    # 运行修复脚本
    import subprocess
    subprocess.run(['python3', os.path.join(base, 'fix_dates.py')], 
                   capture_output=True, text=True, cwd=base)
    
    # 重新加载
    import article_publish_dates
    importlib.reload(article_publish_dates)
    
    # 检查缺失日期
    _missing_dates = []
    for _item in articles_data:
        _slug = _item[0]
        if _slug not in article_publish_dates.ARTICLE_PUBLISH_DATES:
            _missing_dates.append(_slug)
    if _missing_dates:
        print(f"⚠️ 以下文章缺少发布日期: {', '.join(_missing_dates)}")
        print(f"   请在article_publish_dates.py中添加日期")
except Exception as e:
    print(f"⚠️ article_publish_dates处理错误: {e}")

# Load article keyword index for auto-linking
try:
    from article_keywords_data import ARTICLE_KEYWORDS
    print(f"Loaded keyword index for {len(ARTICLE_KEYWORDS)} articles")
except Exception as e:
    ARTICLE_KEYWORDS = {}
    print(f"Error loading keyword index: {e}")

# Shared CSS (inline for single-file deployment per page)
with open(os.path.join(base, '_style.css')) as f:
    CSS = f.read()

def mi(name, alt=''):
    # External image reference (V3 optimization)
    if name.startswith(('comp_', 'howto_', 'uc_')):
        src = f'/images/articles/{name}.jpg'
    else:
        src = f'/images/{name}.jpg'
    return f'<img src="{src}" alt="{alt or name}" loading="lazy">'
def mf(name, alt=''):
    return '<figure class="fig">' + mi(name, alt) + '</figure>'

# Shared components (nav, footer, back-to-top, js, head)
from _components import nav, footer, js, head, full_page, NAV_ITEMS
from _social_share import social_share

print("Helper functions defined")

# ===== URL MAP =====
URL_MAP = {
    'howto_voice_android': '/voice-control-android',
    'howto_texts_handsfree': '/send-texts-hands-free',
    'howto_multistep': '/automate-multi-step-tasks',
    'howto_elderly_setup': '/voice-control-elderly',
    'howto_driving_voice': '/voice-commands-driving',
    'howto_smart_home': '/smart-home-voice-control',
    'uc_commuting': '/voice-control-commuters',
    'uc_seniors': '/ai-phone-seniors',
    'uc_cooking': '/hands-free-cooking',
    'uc_emergency': '/emergency-voice-commands',
    'uc_productivity': '/productivity-automation',
    'uc_visual_impaired': '/voice-control-visually-impaired',
    'uc_parenting': '/parenting-hands-free',
    'uc_fitness': '/voice-fitness',
    'comp_vs_siri': '/foneclaw-vs-siri',
    'comp_vs_google': '/foneclaw-vs-google-assistant',
    'comp_vs_alexa': '/foneclaw-vs-alexa',
    'comp_best_apps': '/best-voice-control-apps-2026',
    'comp_ai_replacing': '/ai-agents-replacing-assistants',
    'comp_vs_gemini': '/gemini-vs-foneclaw',
    'comp_vs_miclaw': '/miclaw-vs-foneclaw',
    'ai-agent-vs-traditional-apps': '/ai-agent-vs-traditional-apps',
    'tasker-alternative-voice-automation': '/tasker-alternative-voice-automation',
    'voice-assistant-privacy-security': '/voice-assistant-privacy-security',
    'voice-control-dirty-hands': '/voice-control-dirty-hands',
    'top-10-ai-agents-2026': '/top-10-ai-agents-2026',
    'hermes-agent-vs-openclaw-vs-foneclaw': '/hermes-agent-vs-openclaw-vs-foneclaw',
    'why-local-ai-agents-never-go-down': '/why-local-ai-agents-never-go-down',
    'automate-instagram-with-voice': '/automate-instagram-with-voice',
    'android-vs-ios-26-5-voice-control': '/android-vs-ios-26-5-voice-control',
    'control-samsung-smart-tv-voice': '/control-samsung-smart-tv-voice',
    'voice-control-wearables': '/voice-control-wearables',
    'small-businesses-use-ai-agents': '/small-businesses-use-ai-agents',
    'cerebras-future-ai-hardware': '/cerebras-future-ai-hardware',
    'trump-phone-mobile-ai': '/trump-phone-mobile-ai',
    'top-10-ai-agent-models-2026': '/top-10-ai-agent-models-2026',
    'ai-phone-war-2026': '/ai-phone-war-2026',
    'ai-terminal-war-agent-battlefield': '/ai-terminal-war-agent-battlefield',
    'xiaomi-ai-ecosystem-2026': '/xiaomi-ai-ecosystem-2026',
    'author/dean': '/author/dean',
    'voice-control-whatsapp': '/voice-control-whatsapp',
    'voice-control-youtube': '/voice-control-youtube',
    'voice-control-tiktok': '/voice-control-tiktok',
    'voice-control-facebook': '/voice-control-facebook',
    'voice-control-twitter': '/voice-control-twitter',
    'voice-control-telegram': '/voice-control-telegram',
    'voice-control-linkedin': '/voice-control-linkedin',
    'voice-control-snapchat': '/voice-control-snapchat',
    'voice-control-reddit': '/voice-control-reddit',
    'voice-control-discord': '/voice-control-discord',
    'claude-ai-login-android': '/claude-ai-login-android',
    'agentic-ai-phone-explained': '/agentic-ai-phone-explained',
    'perplexity-ai-vs-google-search': '/perplexity-ai-vs-google-search',
    'gemini-intelligence-complete-guide': '/gemini-intelligence-complete-guide',
    'gemini-intelligence-features': '/gemini-intelligence-features',
    'ai-agent-phone-control': '/ai-agent-phone-control',
    'xiaomi-miclaw-explained': '/xiaomi-miclaw-explained',
    'huawei-phone-agent': '/huawei-phone-agent',
    'gemini-intelligence-vs-siri': '/gemini-intelligence-vs-siri',
    'miclaw-vs-openclaw': '/miclaw-vs-openclaw',
    'gemini-intelligence-productivity': '/gemini-intelligence-productivity',
    'gemini-intelligence-voice-control': '/gemini-intelligence-voice-control',
    'how-to-install-miclaw': '/how-to-install-miclaw',
    'voice-control-pinterest': '/voice-control-pinterest',
    'xiaomi-lobster-phone-ai-features': '/xiaomi-lobster-phone-ai-features',
    'ai-notification-management': '/ai-notification-management',
    'gemini-intelligence-form-filling': '/gemini-intelligence-form-filling',
    'gemini-intelligence-widgets': '/gemini-intelligence-widgets',
    'gemini-intelligence-supported-devices': '/gemini-intelligence-supported-devices',
    'tencent-phone-agent-cost': '/tencent-phone-agent-cost',
    'xiaomi-phone-agent-summit': '/xiaomi-phone-agent-summit',
    'foneclaw-vs-likeclaw': '/foneclaw-vs-likeclaw',
    'foneclaw-vs-apple-intelligence': '/foneclaw-vs-apple-intelligence',
    'apple-intelligence-accessibility-foneclaw': '/apple-intelligence-accessibility-foneclaw',
    'foneclaw-vs-samsung-galaxy-ai': '/foneclaw-vs-samsung-galaxy-ai',
    'ai-phone-agent-harness': '/ai-phone-agent-harness',
    'mediatek-dimensity-phone-agent': '/mediatek-dimensity-phone-agent',
    'ios-27-siri-ai-agent': '/ios-27-siri-ai-agent',
    'ios-27-siri-gemini-integration': '/ios-27-siri-gemini-integration',
    'copilot-redesign-5-ai-trends-foneclaw': '/copilot-redesign-5-ai-trends-foneclaw',
    'ai-agent-spending-agentic-phone': '/ai-agent-spending-agentic-phone',
    'gemini-intelligence-pixel-9-excluded': '/gemini-intelligence-pixel-9-excluded',
    'samsung-galaxy-s26-ai-features-s25': '/samsung-galaxy-s26-ai-features-s25',
    'foneclaw-vs-openally': '/foneclaw-vs-openally',
    'foneclaw-vs-minimax': '/foneclaw-vs-minimax',
    'foneclaw-vs-all-in-one-ai-agent': '/foneclaw-vs-all-in-one-ai-agent',
    'foneclaw-vs-nebula-ai': '/foneclaw-vs-nebula-ai',
    'skyclaw-vs-foneclaw': '/skyclaw-vs-foneclaw',
    'foneclaw-vs-adobe-firefly': '/foneclaw-vs-adobe-firefly',
    'cloud-vs-local-ai-agent-2026': '/cloud-vs-local-ai-agent-2026',
    'microsoft-ai-super-app-vs-local-agent': '/microsoft-ai-super-app-vs-local-agent',
    'ai-agent-from-lab-to-pocket': '/ai-agent-from-lab-to-pocket',
    'hy-memory-vs-local-agent-memory': '/hy-memory-vs-local-agent-memory',
    'openclaw-security-risks-phone-agent-safer': '/openclaw-security-risks-phone-agent-safer',
    'gemini-spark-vs-foneclaw': '/gemini-spark-vs-foneclaw',
    'wwdc-2026-ai-do-over-phone-agent': '/wwdc-2026-ai-do-over-phone-agent',
    'personal-context-ai-agent-phone': '/personal-context-ai-agent-phone',
    'mcp-invisible-voice-control-phone-agent': '/mcp-invisible-voice-control-phone-agent',
    'apple-local-ai-validates-phone-agent': '/apple-local-ai-validates-phone-agent',
    'workbuddy-vs-foneclaw': '/workbuddy-vs-foneclaw',
    'microsoft-build-2026-ai-agents': '/microsoft-build-2026-ai-agents',
    'nvidia-ai-pc-vs-phone-ai-agent': '/nvidia-ai-pc-vs-phone-ai-agent',
    'apple-ai-glasses-vs-phone-agent': '/apple-ai-glasses-vs-phone-agent',
    'meta-ray-bans-ai-vs-foneclaw': '/meta-ray-bans-ai-vs-foneclaw',
    'ai-agents-rewriting-brand-discovery': '/ai-agents-rewriting-brand-discovery',
    'local-ai-agent-trust-vs-cloud': '/local-ai-agent-trust-vs-cloud',
    'enterprise-ai-agent-security-local': '/enterprise-ai-agent-security-local',
    'ai-agent-token-cost-local-saving': '/ai-agent-token-cost-local-saving',
    'app-intents-apps-machine-callable-ai-agents': '/app-intents-apps-machine-callable-ai-agents',
    'apple-intelligence-pro-subscription-what-to-expect': '/apple-intelligence-pro-subscription-what-to-expect',
    'microsoft-scout-openclaw-ai-agent': '/microsoft-scout-openclaw-ai-agent',
    'os-agent-three-layer-foundation-2026': '/os-agent-three-layer-foundation-2026',
    'ai-chip-custom-race-2026': '/ai-chip-custom-race-2026',
    'self-improving-ai-agents-phone': '/self-improving-ai-agents-phone',
    'eval-driven-phone-agent-measurement': '/eval-driven-phone-agent-measurement',
    'closed-loop-ai-phone-agent-human-in-loop': '/closed-loop-ai-phone-agent-human-in-loop',
    'on-device-llm-optimization-2026': '/on-device-llm-optimization-2026',
    'os-agent-vs-app-traffic-2026': '/os-agent-vs-app-traffic-2026',
    'openai-no-app-phone-voice-hack-night': '/openai-no-app-phone-voice-hack-night',
    'ai-agent-replaces-app-store-developers': '/ai-agent-replaces-app-store-developers',
    'voice-first-phone-2026-landscape': '/voice-first-phone-2026-landscape',
    'xiaomi-miclaw-user-review': '/xiaomi-miclaw-user-review',
    '1000-tps-llms-phone-agent-era': '/1000-tps-llms-phone-agent-era',
    'jd-tencent-ai-agent-shopping-phone-agent': '/jd-tencent-ai-agent-shopping-phone-agent',
    'wechat-ai-agent-commandable-super-app': '/wechat-ai-agent-commandable-super-app',
    'claude-code-multi-agent-system': '/claude-code-multi-agent-system',
}

print(f"URL map: {len(URL_MAP)} article URLs")

# ===== GENERATE PAGES =====
trans_json = json.dumps(translations, ensure_ascii=False)

# ----- HOME PAGE -----
from _homepage import generate_homepage
index_html = generate_homepage(full_page, base, imgs)
with open(os.path.join(base, 'index.html'), 'w', encoding='utf-8') as f:
    f.write(index_html)
print(f"[1/4] index.html: {len(index_html)//1024}KB")

# ----- CHINESE HOME PAGE -----
os.makedirs(os.path.join(base, 'zh'), exist_ok=True)
index_zh_html = generate_homepage(full_page, base, imgs, lang='zh')
with open(os.path.join(base, 'zh', 'index.html'), 'w', encoding='utf-8') as f:
    f.write(index_zh_html)
print(f"[1b] zh/index.html: {len(index_zh_html)//1024}KB")

# ----- TAIWAN TRADITIONAL CHINESE HOME PAGE -----
os.makedirs(os.path.join(base, 'tw'), exist_ok=True)
index_tw_html = generate_homepage(full_page, base, imgs, lang='tw')
with open(os.path.join(base, 'tw', 'index.html'), 'w', encoding='utf-8') as f:
    f.write(index_tw_html)
print(f"[1c] tw/index.html: {len(index_tw_html)//1024}KB")

# ----- FEATURES PAGE -----
from _features_page import generate_features_page
features_html = generate_features_page(full_page, base)
with open(os.path.join(base, 'features.html'), 'w', encoding='utf-8') as f:
    f.write(features_html)
print(f"[2/4] features.html: {len(features_html)//1024}KB")

# ----- CHINESE FEATURES PAGE -----
features_zh_html = generate_features_page(full_page, base, lang='zh')
with open(os.path.join(base, 'zh', 'features.html'), 'w', encoding='utf-8') as f:
    f.write(features_zh_html)
print(f"[2b] zh/features.html: {len(features_zh_html)//1024}KB")

# ----- TAIWAN TRADITIONAL CHINESE FEATURES PAGE -----
features_tw_html = generate_features_page(full_page, base, lang='tw')
with open(os.path.join(base, 'tw', 'features.html'), 'w', encoding='utf-8') as f:
    f.write(features_tw_html)
print(f"[2c] tw/features.html: {len(features_tw_html)//1024}KB")

# ----- COMMUNITY PAGE -----
html = []
html.append(head('FoneClaw Community - Join the Community',
    'Join the FoneClaw community on Telegram, Discord, and X. Get product updates, report bugs, and connect with other users.',
    '/community.html', og_image='https://www.foneclaw.ai/images/home_arch.jpg'))
html.append(nav(4))
html.append('<main>')
html.append('<header style="position:relative;min-height:300px;display:flex;align-items:center;justify-content:center;text-align:center;background:linear-gradient(135deg,#080c18 0%,#0b1a3a 50%,#080c18 100%)"><div style="position:absolute;inset:0;background:radial-gradient(ellipse at center,rgba(0,212,255,0.08) 0%,transparent 70%)"></div><div style="position:relative;z-index:1;padding:60px 20px"><h1 style="font-size:clamp(28px,5vw,44px);font-weight:700;margin-bottom:10px;color:#f0f4f8">Community</h1><p style="color:#8b949e;font-size:17px;max-width:500px;margin:0 auto">Join the movement shaping the future of phone AI</p></div></header>')
html.append('<section style="padding-top:40px;padding-bottom:60px"><div class="wrap"><div class="community-grid" style="display:grid;grid-template-columns:repeat(4,1fr);gap:14px">')
for ic,t,d,b,href in [
    ('<svg viewBox="0 0 24 24" fill="#26A5E4" width="32" height="32"><path d="M11.944 0A12 12 0 0 0 0 12a12 12 0 0 0 12 12 12 12 0 0 0 12-12A12 12 0 0 0 12 0a12 12 0 0 0-.056 0zm4.962 7.224c.1-.002.321.023.465.14a.506.506 0 0 1 .171.325c.016.093.036.306.02.472-.18 1.898-.962 6.502-1.36 8.627-.168.9-.499 1.201-.82 1.23-.696.065-1.225-.46-1.9-.902-1.056-.693-1.653-1.124-2.678-1.8-1.185-.78-.417-1.21.258-1.91.177-.184 3.247-2.977 3.307-3.23.007-.032.014-.15-.056-.212s-.174-.041-.249-.024c-.106.024-1.793 1.14-5.061 3.345-.48.33-.913.49-1.302.48-.428-.008-1.252-.241-1.865-.44-.752-.245-1.349-.374-1.297-.789.027-.216.325-.437.893-.663 3.498-1.524 5.83-2.529 6.998-3.014 3.332-1.386 4.025-1.627 4.476-1.635z"/></svg>','Telegram','Updates and beta access.','Join','https://t.me/foneclaw'),
    ('<svg viewBox="0 0 24 24" fill="#5865F2" width="32" height="32"><path d="M20.317 4.3698a19.7913 19.7913 0 00-4.8851-1.5152.0741.0741 0 00-.0785.0371c-.211.3753-.4447.8648-.6083 1.2495-1.8447-.2762-3.68-.2762-5.4868 0-.1636-.3933-.4058-.8742-.6177-1.2495a.077.077 0 00-.0785-.037 19.7363 19.7363 0 00-4.8852 1.515.0699.0699 0 00-.0321.0277C.5334 9.0458-.319 13.5799.0992 18.0578a.0824.0824 0 00.0312.0561c2.0528 1.5076 4.0413 2.4228 5.9929 3.0294a.0777.0777 0 00.0842-.0276c.4616-.6304.8731-1.2952 1.226-1.9942a.076.076 0 00-.0416-.1057c-.6528-.2476-1.2743-.5495-1.8722-.8923a.077.077 0 01-.0076-.1277c.1258-.0943.2517-.1923.3718-.2914a.0743.0743 0 01.0776-.0105c3.9278 1.7933 8.18 1.7933 12.0614 0a.0739.0739 0 01.0785.0095c.1202.099.246.1981.3728.2924a.077.077 0 01-.0066.1276 12.2986 12.2986 0 01-1.873.8914.0766.0766 0 00-.0407.1067c.3604.698.7719 1.3628 1.225 1.9932a.076.076 0 00.0842.0286c1.961-.6067 3.9495-1.5219 6.0023-3.0294a.077.077 0 00.0313-.0552c.5004-5.177-.8382-9.6739-3.5485-13.6604a.061.061 0 00-.0312-.0286zM8.02 15.3312c-1.1825 0-2.1569-1.0857-2.1569-2.419 0-1.3332.9555-2.4189 2.157-2.4189 1.2108 0 2.1757 1.0952 2.1568 2.419 0 1.3332-.9555 2.4189-2.1569 2.4189zm7.9748 0c-1.1825 0-2.1569-1.0857-2.1569-2.419 0-1.3332.9554-2.4189 2.1569-2.4189 1.2108 0 2.1757 1.0952 2.1568 2.419 0 1.3332-.946 2.4189-2.1568 2.4189z"/></svg>','Discord','Real-time chat and dev discussion.','Join','https://discord.gg/vQ65DUHucj'),
    ('<svg viewBox="0 0 24 24" fill="#fff" width="28" height="28"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"/></svg>','X (Twitter)','Latest news and updates.','Follow','https://x.com/huangda_huang'),
    ('<svg viewBox="0 0 24 24" fill="#1877F2" width="32" height="32"><path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/></svg>','Facebook','Community and updates.','Follow','https://www.facebook.com/foneclaw'),
    ('<svg viewBox="0 0 24 24" fill="#FF0000" width="32" height="32"><path d="M23.498 6.186a3.016 3.016 0 0 0-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.017 3.017 0 0 0 .502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.016 3.016 0 0 0 2.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.015 3.015 0 0 0 2.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814zM9.545 15.568V8.432L15.818 12l-6.273 3.568z"/></svg>','YouTube','Videos and tutorials.','Subscribe','http://www.youtube.com/@foneclaw'),
    ('<svg viewBox="0 0 24 24" fill="#E4405F" width="32" height="32"><path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zM12 0C8.741 0 8.333.014 7.053.072 2.695.272.273 2.69.073 7.052.014 8.333 0 8.741 0 12c0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98C8.333 23.986 8.741 24 12 24c3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98C15.668.014 15.259 0 12 0zm0 5.838a6.162 6.162 0 100 12.324 6.162 6.162 0 000-12.324zM12 16a4 4 0 110-8 4 4 0 010 8zm6.406-11.845a1.44 1.44 0 100 2.881 1.44 1.44 0 000-2.881z"/></svg>','Instagram','Photos and stories.','Follow','https://www.instagram.com/foneclaw/'),
    ('<svg viewBox="0 0 24 24" fill="#FF4500" width="32" height="32"><path d="M12 0A12 12 0 0 0 0 12a12 12 0 0 0 12 12 12 12 0 0 0 12-12A12 12 0 0 0 12 0zm5.01 4.744c.688 0 1.25.561 1.25 1.249a1.25 1.25 0 0 1-2.498.056l-2.597-.547-.8 3.747c1.824.07 3.48.632 4.674 1.488.308-.309.73-.491 1.207-.491.968 0 1.754.786 1.754 1.754 0 .716-.435 1.333-1.01 1.614a3.111 3.111 0 0 1 .042.52c0 2.694-3.13 4.87-7.004 4.87-3.874 0-7.004-2.176-7.004-4.87 0-.183.015-.366.043-.534A1.748 1.748 0 0 1 4.028 12c0-.968.786-1.754 1.754-1.754.463 0 .898.196 1.207.49 1.207-.883 2.878-1.43 4.744-1.487l.885-4.182a.342.342 0 0 1 .14-.197.35.35 0 0 1 .238-.042l2.906.617a1.214 1.214 0 0 1 1.108-.701zM9.25 12C8.561 12 8 12.562 8 13.25c0 .687.561 1.248 1.25 1.248.687 0 1.248-.561 1.248-1.249 0-.688-.561-1.249-1.249-1.249zm5.5 0c-.687 0-1.248.561-1.248 1.25 0 .687.561 1.248 1.249 1.248.688 0 1.249-.561 1.249-1.249 0-.687-.562-1.249-1.25-1.249zm-5.466 3.99a.327.327 0 0 0-.231.094.33.33 0 0 0 0 .463c.842.842 2.484.913 2.961.913.477 0 2.105-.056 2.961-.913a.361.361 0 0 0 .029-.463.33.33 0 0 0-.464 0c-.547.533-1.684.73-2.512.73-.828 0-1.979-.196-2.512-.73a.326.326 0 0 0-.232-.095z"/></svg>','Reddit','Community discussions.','Join','https://www.reddit.com/user/foneclaw/'),
    ('<svg viewBox="0 0 24 24" fill="#00d4ff" width="32" height="32"><path d="M20 4H4c-1.1 0-1.99.9-1.99 2L2 18c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm0 4l-8 5-8-5V6l8 5 8-5v2z"/></svg>','Feedback','Feature requests and bug reports.','Email','mailto:Feedback@foneclaw.ai'),
]:
    html.append(f'<div class="cc"><div class="ci">{ic}</div><h2 style="font-size:18px;font-weight:700;margin-bottom:4px;color:#f0f4f8">{t}</h2><a class="bs" href="{href}" target="_blank" rel="noopener">{b}</a></div>')
html.append('</div></div></section></main>')
html.append(footer())
html.append(social_share())
html.append(js(trans_json))
html.append('</body></html>')
with open(os.path.join(base, 'community.html'), 'w', encoding='utf-8') as f:
    f.write('\n'.join(html))
print(f"[3/4] community.html: {len(''.join(html))//1024}KB")

# ----- ARTICLE PAGES -----
# articles_data loaded from batch files above (19 SEO-optimized articles)


exec(open(os.path.join(base, '_article_template.py')).read())


# ----- AUTHOR PAGE -----

# ----- AUTHOR PAGE (动态生成) -----
import sys
import os
import article_publish_dates
from article_publish_dates import ARTICLE_PUBLISH_DATES
sys.path.insert(0, '/tmp')
from author_generator import generate_author_body

# 生成author页面
author_body = generate_author_body(articles_data, ARTICLE_PUBLISH_DATES, URL_MAP)

author_html = full_page(
    'Dean - Senior Android Engineer & FoneClaw Founder',
    'Dean is a senior Android systems engineer and founder of FoneClaw. Read his articles about AI agents, voice control, and mobile automation.',
    '/author/dean.html',
    -1,
    author_body,
    og_image='https://www.foneclaw.ai/images/og-image.png'
)

# ----- DOWNLOAD PAGE -----
from _download_page import generate_download_page
dl_html = generate_download_page(full_page, base)
with open(os.path.join(base, 'download.html'), 'w', encoding='utf-8') as f:
    f.write(dl_html)
print(f"[5/6] download.html: {len(dl_html)//1024}KB")

# ----- CHINESE DOWNLOAD PAGE -----
dl_zh_html = generate_download_page(full_page, base, lang='zh')
with open(os.path.join(base, 'zh', 'download.html'), 'w', encoding='utf-8') as f:
    f.write(dl_zh_html)
print(f"[5b] zh/download.html: {len(dl_zh_html)//1024}KB")

# ----- TAIWAN TRADITIONAL CHINESE DOWNLOAD PAGE -----
dl_tw_html = generate_download_page(full_page, base, lang='tw')
with open(os.path.join(base, 'tw', 'download.html'), 'w', encoding='utf-8') as f:
    f.write(dl_tw_html)
print(f"[5c] tw/download.html: {len(dl_tw_html)//1024}KB")

# ----- CHINESE COMMUNITY & RESOURCES (generated by standalone scripts) -----
# These are generated by separate scripts and copied to zh/
# Run: python3 gen_zh_community.py && python3 gen_zh_resources.py

# Write author page
os.makedirs(os.path.join(base, 'author'), exist_ok=True)
with open(os.path.join(base, 'author', 'dean.html'), 'w', encoding='utf-8') as f:
    f.write(author_html)
print(f"[6/7] author/dean.html: {len(author_html)//1024}KB")

# ----- EARLY ACCESS PAGE -----
ea_body = '''
<section style="padding:140px 0 80px;text-align:center;position:relative;overflow:hidden">
<div style="position:absolute;top:-200px;left:50%;transform:translateX(-50%);width:800px;height:800px;background:radial-gradient(circle,rgba(0,212,255,.08) 0%,transparent 70%);pointer-events:none"></div>
<div class="wrap" style="position:relative">
<div style="display:inline-block;background:rgba(0,212,255,.1);border:1px solid rgba(0,212,255,.3);color:#00d4ff;font-size:13px;font-weight:600;padding:6px 16px;border-radius:20px;margin-bottom:24px;letter-spacing:.5px">\U0001f680 LAUNCHING SOON</div>
<h1 style="font-size:clamp(32px,5vw,52px);font-weight:700;line-height:1.15;margin-bottom:16px">Your Phone, Your Voice.<br><span style="color:#00d4ff">Zero Touch.</span></h1>
<p style="font-size:clamp(16px,2vw,19px);color:#8b949e;max-width:560px;margin:0 auto 40px;line-height:1.7">FoneClaw is an AI agent that actually controls your Android phone \u2014 not just answers questions. 50+ system operations, cross-app automation, learns your habits.</p>
<div style="display:flex;justify-content:center;gap:48px;margin-bottom:48px;flex-wrap:wrap">
<div style="text-align:center"><div style="font-family:'Space Grotesk',sans-serif;font-size:clamp(28px,4vw,40px);font-weight:700;color:#00d4ff">50+</div><div style="font-size:13px;color:#6e7681;margin-top:4px">Voice Operations</div></div>
<div style="text-align:center"><div style="font-family:'Space Grotesk',sans-serif;font-size:clamp(28px,4vw,40px);font-weight:700;color:#00d4ff">\u221e</div><div style="font-size:13px;color:#6e7681;margin-top:4px">App Integrations</div></div>
<div style="text-align:center"><div style="font-family:'Space Grotesk',sans-serif;font-size:clamp(28px,4vw,40px);font-weight:700;color:#00d4ff">$0</div><div style="font-size:13px;color:#6e7681;margin-top:4px">Core Features Free</div></div>
</div>
<div style="background:linear-gradient(135deg,rgba(0,212,255,.05),rgba(13,17,23,.8));border:1px solid rgba(0,212,255,.15);border-radius:16px;padding:40px;max-width:480px;margin:0 auto">
<h2 style="font-size:22px;margin-bottom:6px;text-align:center">Get Early Access</h2>
<p style="text-align:center;color:#6e7681;font-size:14px;margin-bottom:28px">Be the first to know when FoneClaw launches.</p>
<form id="signupForm" onsubmit="return handleSubmit(event)">
<div style="margin-bottom:18px"><label style="display:block;font-size:13px;font-weight:600;color:#c9d1d9;margin-bottom:6px">Name</label><input type="text" id="name" name="name" placeholder="Your name" required autocomplete="name" style="width:100%;padding:12px 16px;background:#0d1117;border:1px solid #21262d;border-radius:10px;color:#f0f4f8;font-size:15px;font-family:'Inter',sans-serif;outline:none"></div>
<div style="margin-bottom:18px"><label style="display:block;font-size:13px;font-weight:600;color:#c9d1d9;margin-bottom:6px">Email</label><input type="email" id="email" name="email" placeholder="you@example.com" required autocomplete="email" style="width:100%;padding:12px 16px;background:#0d1117;border:1px solid #21262d;border-radius:10px;color:#f0f4f8;font-size:15px;font-family:'Inter',sans-serif;outline:none"></div>
<div style="margin-bottom:18px"><label style="display:block;font-size:13px;font-weight:600;color:#c9d1d9;margin-bottom:6px">Social Media <span style="color:#6e7681;font-weight:400">(optional)</span></label><input type="text" id="social" name="social" placeholder="@twitter / @instagram / etc." style="width:100%;padding:12px 16px;background:#0d1117;border:1px solid #21262d;border-radius:10px;color:#f0f4f8;font-size:15px;font-family:'Inter',sans-serif;outline:none"></div>
<button type="submit" id="submitBtn" style="width:100%;padding:14px;background:linear-gradient(135deg,#00d4ff,#0099cc);color:#080c18;font-family:'Space Grotesk',sans-serif;font-size:16px;font-weight:700;border:none;border-radius:10px;cursor:pointer;margin-top:8px">Join the Waitlist \u2192</button>
<p style="text-align:center;font-size:12px;color:#484f58;margin-top:14px">\U0001f512 No spam. Unsubscribe anytime.</p>
</form>
<div id="successMsg" style="display:none;text-align:center;padding:20px 0">
<div style="font-size:48px;margin-bottom:12px">\U0001f389</div>
<h3 style="font-size:20px;color:#3fb950;margin-bottom:8px">You're on the list!</h3>
<p style="color:#8b949e;font-size:14px">We'll notify you as soon as FoneClaw is ready.<br>Check your inbox for a confirmation.</p>
</div>
</div>
</div>
</section>
<section style="padding:60px 0 40px;text-align:center"><div class="wrap"><h2 style="font-size:clamp(22px,3vw,30px);margin-bottom:8px">What FoneClaw Can Do</h2><p style="color:#8b949e;font-size:15px;margin-bottom:40px">A glimpse of what's coming</p>
<div style="display:grid;grid-template-columns:repeat(3,1fr);gap:24px">
<div style="background:rgba(13,17,23,.6);border:1px solid #1a2332;border-radius:12px;padding:28px 20px;text-align:center"><div style="font-size:32px;margin-bottom:12px">\U0001f5e3\ufe0f</div><h3 style="font-size:15px;margin-bottom:6px">Voice-First Control</h3><p style="font-size:13px;color:#6e7681">Calls, texts, apps, settings \u2014 all by voice. No screen tapping needed.</p></div>
<div style="background:rgba(13,17,23,.6);border:1px solid #1a2332;border-radius:12px;padding:28px 20px;text-align:center"><div style="font-size:32px;margin-bottom:12px">\U0001f517</div><h3 style="font-size:15px;margin-bottom:6px">Cross-App Automation</h3><p style="font-size:13px;color:#6e7681">"Order my usual on DoorDash and play my Spotify playlist" \u2014 one command.</p></div>
<div style="background:rgba(13,17,23,.6);border:1px solid #1a2332;border-radius:12px;padding:28px 20px;text-align:center"><div style="font-size:32px;margin-bottom:12px">\U0001f9e0</div><h3 style="font-size:15px;margin-bottom:6px">Memory &amp; Learning</h3><p style="font-size:13px;color:#6e7681">Remembers your habits, preferences, and routines. Gets smarter every day.</p></div>
<div style="background:rgba(13,17,23,.6);border:1px solid #1a2332;border-radius:12px;padding:28px 20px;text-align:center"><div style="font-size:32px;margin-bottom:12px">\U0001f697</div><h3 style="font-size:15px;margin-bottom:6px">Driving Mode</h3><p style="font-size:13px;color:#6e7681">Hands-free everything on the road. Navigate, call, text \u2014 safely.</p></div>
<div style="background:rgba(13,17,23,.6);border:1px solid #1a2332;border-radius:12px;padding:28px 20px;text-align:center"><div style="font-size:32px;margin-bottom:12px">\U0001f3e0</div><h3 style="font-size:15px;margin-bottom:6px">Smart Home Hub</h3><p style="font-size:13px;color:#6e7681">Control lights, thermostats, cameras \u2014 all through your phone's AI.</p></div>
<div style="background:rgba(13,17,23,.6);border:1px solid #1a2332;border-radius:12px;padding:28px 20px;text-align:center"><div style="font-size:32px;margin-bottom:12px">\U0001f474</div><h3 style="font-size:15px;margin-bottom:6px">Elderly Friendly</h3><p style="font-size:13px;color:#6e7681">Simple voice commands for seniors. No complex menus or tiny buttons.</p></div>
</div></div></section>
<script>
const FORM_ENDPOINT='https://script.google.com/macros/s/AKfycbzUj64cBq8yH4OYSDxG7yE1Kq-qSBA4_oN8lfMY3eNYTJTkGO6a7GC_dPUCBHE_iH4DJA/exec';
async function handleSubmit(e){e.preventDefault();const btn=document.getElementById('submitBtn');const form=document.getElementById('signupForm');const success=document.getElementById('successMsg');btn.disabled=true;btn.textContent='Submitting...';const data={name:document.getElementById('name').value.trim(),email:document.getElementById('email').value.trim(),social:document.getElementById('social').value.trim(),_source:'early-access.html'};try{await fetch(FORM_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data),mode:'no-cors'});form.style.display='none';success.style.display='block';gtag('event','generate_lead',{form_name:'early-access',form_destination:'early-access.html',form_id:'signupForm'});}catch(err){const entries=JSON.parse(localStorage.getItem('foneclaw_signups')||'[]');entries.push({...data,timestamp:new Date().toISOString()});localStorage.setItem('foneclaw_signups',JSON.stringify(entries));form.style.display='none';success.style.display='block';gtag('event','generate_lead',{form_name:'early-access',form_destination:'early-access.html',form_id:'signupForm'});}return false;}
</script>
'''

ea_html = full_page('FoneClaw - Coming Soon | Be the First to Try',
    'FoneClaw is launching soon. Sign up to get early access to the AI agent that controls your Android phone entirely by voice.',
    '/early-access.html', -1, ea_body, og_image='https://www.foneclaw.ai/images/feat_agent.jpg')
with open(os.path.join(base, 'early-access.html'), 'w', encoding='utf-8') as f:
    f.write(ea_html)
print(f"[6/6] early-access.html: {len(ea_html)//1024}KB")


# ----- PRIVACY PAGE -----
privacy_body = """
<div class="art-wrap">
<div class="breadcrumb"><a href="/">Home</a><span class="sep">\u203a</span><span>Privacy Policy</span></div>
<header class="art-header"><div class="cat">Legal</div><div class="meta-row"><span>\U0001f4c5 May 9, 2026</span><span>\u23f1\ufe0f 5 min read</span></div><h1>Privacy Policy</h1><p class="art-desc">How FoneClaw collects, uses, and protects your personal information.</p></header>
<div class="art-body">
<h2 id="information-we-collect"><a class="anchor" href="#information-we-collect">#</a>Information We Collect</h2>
<p>FoneClaw collects minimal data necessary to provide voice-controlled phone automation. This includes voice commands processed locally on your device, app usage patterns stored only on your device for learning preferences, and optional cloud processing data that is encrypted and deleted immediately after use. We do not collect browsing history, contacts, or message content.</p>

<h2 id="how-we-use-information"><a class="anchor" href="#how-we-use-information">#</a>How We Use Your Information</h2>
<p>We use collected information solely to provide and improve FoneClaw services. Voice commands are processed to execute your requested actions. Usage patterns help us personalize your experience. We never sell your data to third parties or use it for advertising purposes.</p>

<h2 id="data-storage-security"><a class="anchor" href="#data-storage-security">#</a>Data Storage and Security</h2>
<p>Your data is stored locally on your device by default. When cloud processing is enabled for specific features, data is encrypted in transit and at rest using industry-standard AES-256 encryption. Cloud data is automatically deleted within 24 hours of processing.</p>

<h2 id="third-party-services"><a class="anchor" href="#third-party-services">#</a>Third-Party Services</h2>
<p>FoneClaw integrates with third-party services (Google Maps, Spotify, etc.) only when you explicitly authorize them. Each integration follows the respective service privacy policy. We do not share your data between third-party services.</p>

<h2 id="your-rights"><a class="anchor" href="#your-rights">#</a>Your Rights</h2>
<p>You have the right to access, modify, or delete your personal data at any time. You can export your data, opt out of cloud processing, or delete your account entirely through the FoneClaw settings menu.</p>

<h2 id="children-privacy"><a class="anchor" href="#children-privacy">#</a>Children Privacy</h2>
<p>FoneClaw is not intended for children under 13. We do not knowingly collect personal information from children. If you believe a child has provided us with personal data, please contact us immediately.</p>

<h2 id="changes-policy"><a class="anchor" href="#changes-policy">#</a>Changes to This Policy</h2>
<p>We may update this privacy policy periodically. Significant changes will be communicated through the FoneClaw app and website. Continued use after changes constitutes acceptance of the updated policy.</p>

<h2 id="contact-us"><a class="anchor" href="#contact-us">#</a>Contact Us</h2>
<p>For privacy-related questions or concerns, contact us at Feedback@foneclaw.ai. We respond to all privacy inquiries within 48 hours.</p>
</div>
</div>
"""

privacy_html = full_page('Privacy Policy - FoneClaw',
    'FoneClaw privacy policy: how we collect, use, and protect your personal data. Learn about data retention, third-party sharing, and your privacy rights.',
    '/privacy.html', -1, privacy_body, og_image='https://www.foneclaw.ai/images/feat_memory.jpg')
with open(os.path.join(base, 'privacy.html'), 'w', encoding='utf-8') as f:
    f.write(privacy_html)
print(f"[7/7] privacy.html: {len(privacy_html)//1024}KB")



# ----- RESOURCES PAGE -----
# Generate resources page (hub entry page)
from _resources_hub import generate_resources_page
resources_html = generate_resources_page(full_page, base)
with open(os.path.join(base, 'resources.html'), 'w', encoding='utf-8') as f:
    f.write(resources_html)
print(f"[8/8] resources.html: {len(resources_html)//1024}KB")


# Generate hub pages
from _hub_pages import generate_hub_pages
generate_hub_pages(base)
print("[8/8] Hub pages generated")

# Generate sitemap
sitemap_urls = [
    ('https://www.foneclaw.ai/', 'weekly', '1.0'),
    ('https://www.foneclaw.ai/features.html', 'monthly', '0.8'),
    ('https://www.foneclaw.ai/resources.html', 'monthly', '0.8'),
    ('https://www.foneclaw.ai/community.html', 'monthly', '0.6'),
    ('https://www.foneclaw.ai/privacy.html', 'yearly', '0.3'),
    ('https://www.foneclaw.ai/download.html', 'monthly', '0.8'),
    ('https://www.foneclaw.ai/early-access.html', 'weekly', '0.9'),
    # Hub pages
    ('https://www.foneclaw.ai/voice-control/index.html', 'weekly', '0.9'),
    ('https://www.foneclaw.ai/comparisons/index.html', 'weekly', '0.9'),
    ('https://www.foneclaw.ai/ai-agent/index.html', 'weekly', '0.9'),
    ('https://www.foneclaw.ai/news/index.html', 'weekly', '0.9'),
    # Sub-hub pages
    ('https://www.foneclaw.ai/comparisons/foneclaw-vs/index.html', 'weekly', '0.8'),
    ('https://www.foneclaw.ai/comparisons/tech-analysis/index.html', 'weekly', '0.8'),
    ('https://www.foneclaw.ai/ai-agent/gemini-intelligence/index.html', 'weekly', '0.8'),
    ('https://www.foneclaw.ai/ai-agent/other/index.html', 'weekly', '0.8'),
]
for art_id, url in URL_MAP.items():
    sitemap_urls.append((f'https://www.foneclaw.ai{url}.html', 'weekly', '0.7'))

sitemap = '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
for loc, freq, pri in sitemap_urls:
    sitemap += f'  <url><loc>{loc}</loc><changefreq>{freq}</changefreq><priority>{pri}</priority></url>\n'
sitemap += '</urlset>'
with open(os.path.join(base, 'sitemap.xml'), 'w') as f:
    f.write(sitemap)
print(f"sitemap.xml: {len(sitemap_urls)} URLs")

# Generate robots.txt
robots = 'User-agent: *\nAllow: /\n\nUser-agent: facebookexternalhit\nAllow: /\n\nUser-agent: Googlebot\nAllow: /\n\nUser-agent: Twitterbot\nAllow: /\n\nSitemap: https://www.foneclaw.ai/sitemap.xml\n'
with open(os.path.join(base, 'robots.txt'), 'w') as f:
    f.write(robots)
print("robots.txt updated")

print("\n===== BUILD COMPLETE =====")
print(f"Pages generated:")
print(f"  / (index.html)")
print(f"  /features (features.html)")
print(f"  /community (community.html)")
print(f"  + {count} article pages")
print(f"  Total: {count + 3} pages with unique URLs")

# === 自动复制到upload文件夹（只复制新文章和内容变化的文章）===
import glob
import shutil
import hashlib

upload_dir = os.path.expanduser("~/foneclaw-deploy/uploads/2026-05-25_1750")

def file_hash(filepath):
    """计算文件的MD5哈希值"""
    with open(filepath, 'rb') as f:
        return hashlib.md5(f.read()).hexdigest()

# 复制新文章和内容变化的文章
# 先保存upload文件夹中文件的MD5哈希
upload_hashes = {}
for html_file in glob.glob(os.path.join(upload_dir, "*.html")):
    filename = os.path.basename(html_file)
    upload_hashes[filename] = file_hash(html_file)

new_articles = []
updated_articles = []

for html_file in glob.glob(os.path.join(base, "*.html")):
    filename = os.path.basename(html_file)
    upload_path = os.path.join(upload_dir, filename)
    
    if not os.path.exists(upload_path):
        # 新文章（upload文件夹中不存在）
        shutil.copy2(html_file, upload_dir)
        new_articles.append(filename)
    elif file_hash(html_file) != upload_hashes.get(filename, ''):
        # 内容变化的文章
        shutil.copy2(html_file, upload_dir)
        updated_articles.append(filename)

# 复制author目录（总是复制，因为可能有新文章）
author_src = os.path.join(base, "author")
author_dst = os.path.join(upload_dir, "author")
if os.path.exists(author_dst):
    shutil.rmtree(author_dst)
shutil.copytree(author_src, author_dst)

# 复制resources和sitemap（总是复制，因为可能有新文章）
# Copy sub-hub files
# Generate sub-hub pages (after copy)
# Note: sub-hub pages are generated directly to upload_dir by _subhub_pages.py
# No need to copy from base - the generator writes directly to deploy folder
from _subhub_pages import generate_subhub_pages
generate_subhub_pages(base)
for f in ["resources.html", "sitemap.xml"]:
    src = os.path.join(base, f)
    if os.path.exists(src):
        shutil.copy2(src, upload_dir)

# 复制新文章的图片（如果upload文件夹中不存在）
img_src_dir = os.path.join(base, "images", "articles")
img_dst_dir = os.path.join(upload_dir, "images", "articles")
if os.path.exists(img_src_dir):
    for img_file in os.listdir(img_src_dir):
        img_src = os.path.join(img_src_dir, img_file)
        img_dst = os.path.join(img_dst_dir, img_file)
        if not os.path.exists(img_dst):
            shutil.copy2(img_src, img_dst)

print(f"\n✅ 已自动复制到 {upload_dir}")
if new_articles:
    print(f"新文章: {new_articles}")
else:
    print("无新文章更新")
