#!/usr/bin/env python3
# Strict multilingual QA for FoneClaw localized core pages and selected articles.
# Generated by Hermes for pre-publish verification.
from pathlib import Path
from bs4 import BeautifulSoup
import re, json, sys, html

ROOT = Path(__file__).resolve().parent
LANGS = ['zh','tw','ja','ko','es','pt']
CORE_PAGES = ['index.html','features.html','download.html','resources.html','community.html']
SLUGS = [
 'tasker-alternative-voice-automation',
 'xiaomi-ai-ecosystem-2026',
 'voice-control-visually-impaired',
 'gemini-intelligence-supported-devices',
 'comp_vs_miclaw',
 'wwdc-2026-ai-do-over-phone-agent',
 'agentic-ai-phone-explained',
 'gemini-vs-foneclaw',
 'android-vs-ios-26-5-voice-control',
 'voice-control-whatsapp',
 'gemini-intelligence-vs-siri',
 'foneclaw-vs-apple-intelligence',
]
LANG_NAME = {'zh':'Simplified Chinese','tw':'Traditional Chinese','ja':'Japanese','ko':'Korean','es':'Spanish','pt':'Portuguese'}
EXPECTED_HTML_LANG = {'zh':'zh','tw':'tw','ja':'ja','ko':'ko','es':'es','pt':'pt'}
EXPECTED_HREFLANG = {'zh':'zh','tw':'zh-TW','ja':'ja','ko':'ko','es':'es','pt':'pt'}

BANNED_EN = [
 'delve','leverage','utilize','cutting-edge','seamless','revolutionize','harness','unlock','embark','robust','innovative','game-changer','absolutely','furthermore','moreover','additionally','incredibly','fundamentally','unparalleled','empower','revolutionary','realm'
]
AI_PHRASES = ["here's the thing", "but there's a catch", "let me explain", "now you might be wondering", "the bottom line", "think about it this way", "we have all been there", "imagine your", "imagine this", "imagine that", "in this article", "in conclusion", "to summarize"]
ZH_BAD = ['电话代理','手机代理','智能体','代理','永久免费','无需信用卡','不只是回答问题']
ZH_REQUIRED_IDEAS = ['Android', '手机', 'AI']
TW_BAD = ['电话代理','手機代理','智能體','代理','永久免費','無需信用卡']
KO_BAD = ['음성 조작','Pro 플랜','Root 없이','노코드','영원히 무료','무조건']
JA_BAD = ['永遠に無料','プロキシ','エージェントプロキシ']
ES_BAD = ['gratis para siempre']
PT_BAD = ['grátis para sempre']
BAD_BY_LANG = {'zh':ZH_BAD,'tw':TW_BAD,'ko':KO_BAD,'ja':JA_BAD,'es':ES_BAD,'pt':PT_BAD}
EEAT = {
 'zh':['根据我们的','在我们的测试','我们的经验','实际测试','我们的分析','我们在'],
 'tw':['根據我們的','在我們的測試','我們的經驗','實際測試','我們的分析','我們在'],
 'ja':['私たちのテスト','私たちの経験','実際のテスト','私たちの分析','検証では'],
 'ko':['우리의 테스트','우리의 경험','실제 테스트','우리의 분석','검증 결과'],
 'es':['nuestra experiencia','nuestras pruebas','nuestro análisis','según nuestro','en nuestras pruebas','basándonos'],
 'pt':['nossa experiência','nossos testes','nossas análises','nossa análise','com base','em nossos testes','analisando'],
}
FAQ_HEADINGS = {
 'zh':['常见问题','常見問題'], 'tw':['常見問題'], 'ja':['よくある質問'], 'ko':['자주 묻는 질문'], 'es':['Preguntas frecuentes'], 'pt':['Perguntas frequentes']
}
CJK_RE = re.compile(r'[\u3400-\u4dbf\u4e00-\u9fff\u3040-\u30ff\uac00-\ud7a3]')
ZH_CHAR_RE = re.compile(r'[\u4e00-\u9fff]')

# Some English product/brand names are allowed in non-English pages.
ALLOWED_EN = {'FoneClaw','Android','AI','APK','Google','Gemini','Siri','Apple','MiClaw','MiMo','Xiaomi','WhatsApp','Tasker','iOS','WWDC','Phone','Health','Daily','Brief','Passive','Triggers','USB','ADB','Beta','Telegram','LinkedIn','Reddit','Facebook','YouTube'}

results=[]
def add(level, lang, page, check, msg):
    results.append({'level':level,'lang':lang,'page':page,'check':check,'msg':msg})

def read(path):
    try: return path.read_text(encoding='utf-8')
    except Exception as e:
        add('FAIL','-',str(path.relative_to(ROOT)),'read',str(e)); return ''

def soup_text(soup):
    for tag in soup(['script','style','noscript']): tag.decompose()
    return soup.get_text('\n', strip=True)

def clean_words(text):
    return re.findall(r"[A-Za-z][A-Za-z\-']+", text)

def english_residue(text):
    words=[w for w in clean_words(text) if len(w)>3 and w not in ALLOWED_EN]
    # Ignore URLs-ish and css residues via visible text already minimized.
    return sorted(set(words))[:30]

def body_node(soup):
    return soup.select_one('.art-body') or soup.select_one('article') or soup.select_one('main') or soup.body or soup

def article_scope(soup):
    return soup.select_one('article') or soup.select_one('main') or soup.body or soup

def count_body_length(lang, text):
    if lang in ['zh','tw','ja','ko']:
        return len(CJK_RE.findall(text))
    return len(re.findall(r'\b\w+\b', text))

def internal_links(body):
    hrefs=[]
    for a in body.select('a[href]'):
        h=a.get('href','')
        if h.startswith('/') and h.endswith('.html'):
            hrefs.append(h)
        elif re.match(r'^[a-z0-9_\-/]+\.html', h):
            hrefs.append(h)
    # Exclude same-page anchors and assets.
    return sorted(set(hrefs))

def validate_head(lang, soup, page, is_article=False):
    html_lang = soup.html.get('lang','') if soup.html else ''
    if html_lang != EXPECTED_HTML_LANG[lang]:
        add('FAIL',lang,page,'html_lang',f'html lang={html_lang!r}, expected {EXPECTED_HTML_LANG[lang]!r}')
    title = soup.title.get_text(strip=True) if soup.title else ''
    if not title:
        add('FAIL',lang,page,'title','missing title')
    elif len(title) > 60:
        add('FAIL',lang,page,'title_length',f'{len(title)} chars: {title[:90]}')
    desc_tag = soup.find('meta', attrs={'name':'description'})
    desc = desc_tag.get('content','').strip() if desc_tag else ''
    if not desc:
        add('FAIL',lang,page,'meta','missing description')
    elif not (120 <= len(desc) <= 160):
        add('FAIL',lang,page,'meta_length',f'{len(desc)} chars: {desc[:90]}')
    can = soup.find('link', rel='canonical')
    if not can or not can.get('href'):
        add('FAIL',lang,page,'canonical','missing canonical')
    elif f'/{lang}/' not in can.get('href',''):
        add('FAIL',lang,page,'canonical',f'canonical not same-lang: {can.get("href")}')
    alts = {a.get('hreflang'):a.get('href','') for a in soup.find_all('link', rel='alternate')}
    for code in ['en','zh','zh-TW','ja','ko','es','pt','x-default']:
        if code not in alts:
            add('FAIL',lang,page,'hreflang',f'missing {code}')
        elif alts[code] == '':
            add('FAIL',lang,page,'hreflang',f'empty href for {code}')
    if EXPECTED_HREFLANG[lang] in alts and f'/{lang}/' not in alts[EXPECTED_HREFLANG[lang]]:
        add('FAIL',lang,page,'hreflang_self',f'self alt wrong: {alts[EXPECTED_HREFLANG[lang]]}')
    scripts=soup.find_all('script', attrs={'type':'application/ld+json'})
    if is_article and not scripts:
        add('FAIL',lang,page,'schema','missing JSON-LD')
    for sc in scripts:
        try: json.loads(sc.string or sc.get_text())
        except Exception as e: add('FAIL',lang,page,'schema_json',str(e))

def validate_copy(lang, soup, page, core=False):
    # soup_text() is destructive because it decomposes script/style tags.
    # Always parse a copy so later structural checks (FAQ, schema, images) still see the original tree.
    text=soup_text(BeautifulSoup(str(soup), 'html.parser'))
    lower=text.lower()
    for w in BANNED_EN:
        if re.search(r'\b'+re.escape(w)+r'\b', lower):
            add('FAIL',lang,page,'banned_word',w)
    for p in AI_PHRASES:
        if p in lower:
            add('FAIL',lang,page,'ai_phrase',p)
    for bad in BAD_BY_LANG.get(lang,[]):
        if bad.lower() in lower:
            add('FAIL',lang,page,'localized_bad_term',bad)
    if lang in ['zh','tw']:
        # Only flag visible standalone English "phone". Do not flag iPhone, URL slugs, or brand/product names.
        if re.search(r'(?<![A-Za-z])phone(?![A-Za-z])', lower):
            add('WARN',lang,page,'english_residue','visible standalone English "phone" outside allowed phrase')
    if lang not in ['es','pt']:
        residues=english_residue(text)
        if core and len(residues)>12:
            add('WARN',lang,page,'english_residue',', '.join(residues[:20]))
    if core:
        # Product fact guardrails
        if ('forever' in lower or '永久' in text or '永遠' in text or '영원' in text) and ('免费' in text or '免費' in text or '무료' in text or 'free' in lower):
            add('FAIL',lang,page,'pricing_claim','possible forever-free claim')
        if ('iPhone' in text or 'iOS' in text) and 'Android' not in text:
            add('WARN',lang,page,'positioning','mentions iOS/iPhone without Android context')

def validate_core():
    for lang in LANGS:
        for p in CORE_PAGES:
            path=ROOT/lang/p
            page=f'{lang}/{p}'
            if not path.exists():
                add('FAIL',lang,page,'exists','missing core page')
                continue
            soup=BeautifulSoup(read(path),'html.parser')
            validate_head(lang,soup,page,False)
            validate_copy(lang,soup,page,True)
            h1=soup.find_all('h1')
            if len(h1)!=1:
                add('FAIL',lang,page,'h1',f'{len(h1)} H1 tags')
            # language selector absolute URL + selected option
            selects=soup.select('select.lang-sel')
            if not selects:
                add('FAIL',lang,page,'language_switcher','missing .lang-sel')
            else:
                sel=selects[0]
                if sel.get('data-lang') != lang:
                    add('FAIL',lang,page,'language_switcher',f'data-lang={sel.get("data-lang")}')
                vals=[o.get('value','') for o in sel.select('option')]
                if any(v.startswith('/') or v.startswith('./') for v in vals):
                    add('FAIL',lang,page,'language_switcher','non-absolute option URL')
                selected=[o for o in sel.select('option') if o.has_attr('selected')]
                if not selected:
                    add('FAIL',lang,page,'language_switcher','no selected option')
            if p=='features.html':
                text=soup_text(soup)
                english_cats=['Phone Status','Notifications','Contacts','Calendar','System Settings','File & Media','Connectivity','Security & Privacy']
                hits=[x for x in english_cats if re.search(r'(?<![A-Za-z])' + re.escape(x) + r'(?![A-Za-z])', text)]
                if hits:
                    add('FAIL',lang,page,'features_categories_english',', '.join(hits))

def validate_articles():
    for lang in LANGS:
        for slug in SLUGS:
            path=ROOT/lang/(slug+'.html')
            page=f'{lang}/{slug}.html'
            if not path.exists():
                add('FAIL',lang,page,'exists','missing article')
                continue
            soup=BeautifulSoup(read(path),'html.parser')
            validate_head(lang,soup,page,True)
            validate_copy(lang,soup,page,False)
            h1=soup.find_all('h1')
            if len(h1)!=1: add('FAIL',lang,page,'h1',f'{len(h1)} H1 tags')
            body=body_node(soup)
            scope=article_scope(soup)
            body_text=soup_text(BeautifulSoup(str(body),'html.parser'))
            scope_text=soup_text(BeautifulSoup(str(scope),'html.parser'))
            h2=[x.get_text(' ',strip=True) for x in scope.select('h2')]
            if len(h2)<7:
                add('FAIL',lang,page,'h2_count',f'{len(h2)} H2: {h2}')
            faq_text='\n'.join(h2) + '\n' + scope_text
            if not any(x in faq_text for x in FAQ_HEADINGS.get(lang,[])):
                add('FAIL',lang,page,'faq_heading',f'headings={h2[-3:]}')
            # count FAQ questions rendered in the whole article scope, not only .art-body
            faq_q = len(scope.select('.faq-q')) + len([x for x in scope.select('h3') if '?' in x.get_text() or '？' in x.get_text()])
            if faq_q < 4:
                add('FAIL',lang,page,'faq_count',f'{faq_q} questions')
            patterns=EEAT.get(lang,[])
            eeat_hits=[p for p in patterns if p.lower() in body_text.lower()]
            if len(eeat_hits)<3:
                add('FAIL',lang,page,'eeat',f'{len(eeat_hits)} patterns: {eeat_hits}')
            first_section=body_text[:900].lower()
            if not any(p.lower() in first_section for p in patterns):
                add('FAIL',lang,page,'eeat_intro','missing E-E-A-T in first section')
            length=count_body_length(lang, body_text)
            min_len=1500 if lang in ['zh','tw','ja','ko'] else 1000
            max_len=5000 if lang in ['zh','tw','ja','ko'] else 2300
            if not (min_len <= length <= max_len):
                add('FAIL',lang,page,'body_length',f'{length}, expected {min_len}-{max_len}')
            links=internal_links(body)
            if len(links)<5:
                add('FAIL',lang,page,'internal_links',f'{len(links)} unique body links: {links}')
            # Markdown residue
            if re.search(r'\[[^\]]+\]\([^\)]+\)', body_text):
                add('FAIL',lang,page,'markdown_residue','raw markdown link found')
            imgs=soup.select('img')
            # Accept page-level article hero images; they do not have to live inside .art-body.
            if not imgs and not (soup.find('meta', property='og:image') or soup.find('meta', attrs={'name':'twitter:image'})):
                add('FAIL',lang,page,'images','no page image or og:image')
            for img in imgs:
                if not img.get('alt','').strip():
                    add('FAIL',lang,page,'image_alt','img missing alt')

def validate_sitemap():
    path=ROOT/'sitemap.xml'
    if not path.exists():
        add('FAIL','-','sitemap.xml','exists','missing sitemap')
        return
    s=read(path)
    if 'href=""' in s:
        add('FAIL','-','sitemap.xml','empty_href','contains empty href')
    for lang in LANGS:
        cnt=s.count(f'https://foneclaw.ai/{lang}/') + s.count(f'https://www.foneclaw.ai/{lang}/')
        if cnt < 17:
            add('FAIL',lang,'sitemap.xml','localized_url_count',f'{cnt} refs, expected at least 17 loc/hreflang refs')

validate_core()
validate_articles()
validate_sitemap()

# Print grouped summary
fails=[r for r in results if r['level']=='FAIL']
warns=[r for r in results if r['level']=='WARN']
print(f'STRICT QA RESULTS: FAIL={len(fails)} WARN={len(warns)} TOTAL={len(results)}')
from collections import Counter, defaultdict
print('Failures by check:')
for k,v in Counter(r['check'] for r in fails).most_common(): print(f'  {k}: {v}')
print('Failures by lang:')
for k,v in Counter(r['lang'] for r in fails).most_common(): print(f'  {k}: {v}')
print('\nFIRST 200 ISSUES:')
for r in results[:200]:
    print(f"{r['level']} [{r['lang']}] {r['page']} :: {r['check']} :: {r['msg']}")

out=ROOT/'qa_multilingual_strict_report.json'
out.write_text(json.dumps(results, ensure_ascii=False, indent=2), encoding='utf-8')
print(f'Wrote {out}')
sys.exit(1 if fails else 0)
